### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_6_Green-Development-Planner#52]
Major:
- [x] Switch lines chart to two cards 
- [x] Color and styling in general, separate columns more clear? Not sure this is needed, but explore and see if you like it more.
- [x] Map outline on hover, map click update right side?

Minor:
- [x] Separation between map and other charts
- [x] Different style for title, not serif font
- [x] Switch map projection from mercator?
- [x] Title mention "consumption" of left donut
- [x] Remove three dots actions buttons because there are many overlapping ones.
- [x] "Selected entity" to cameroon
- [x] Color scale below map

**Comment by yhan178** [comment]
Thank you Joel, our new app has addressed all of above suggestions.
Major:
- Switch lines chart to two cards #59
- Color and styling in general, separate columns more clear? Not sure this is needed, but explore and see if you like it more. #60
- Map outline on hover, map click update right side? #59

Minor:
- Separation between map and other charts, #78 
- Different style for title, not serif font, #60
- Switch map projection from mercator? #59
- Title mention "consumption" of left donut #60
- Remove three dots actions buttons because there are many overlapping ones. #59
- "Selected entity" to cameroon #60
- Color scale below map #59
